server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bank
  application:
    name: bank-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8099/eureka/
