server:
  port: 8082
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/credit
  application:
    name: credit-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8099/eureka/
